bases:
- ../../base

# /!\ important !
# https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_namespacetransformer_
namespace: vote-pr-30914

patches:
- target:
    kind: Service
    name: vote
    namespace: vote
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30914

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: vote
    namespace: vote
  spec:
    template:
      spec:
        containers:
          - name: vote
            image: 789037212033.dkr.ecr.us-east-1.amazonaws.com/pull-request-vote-pr-30914:54eeee9a010644e7c5d75c4a19aa7e7f43b02ef5
            env:
            - name: VERSION
              value: 54eeee9a010644e7c5d75c4a19aa7e7f43b02ef5
