apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: vote
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      app: vote
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: ${vote_image}
        env:
          - name: NODE_ENV
            value: production
          - name: VERSION
            value: "0.0.1"
          - name: WEBSITE_PORT
            value: "3000"
          - name: POSTGRES_USER
            value: "admin"
          - name: POSTGRES_HOST
            value: "postgres"
          - name: POSTGRES_DATABASE
            value: "vote"
          - name: POSTGRES_PASSWORD
            value: "password"
          - name: POSTGRES_PORT
            value: "5432"
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: aws-ecr-auth-docker-config
