bases:
- ../../base

# /!\ important !
# https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_namespacetransformer_
namespace: vote-pr-5

patches:
- target:
    kind: Service
    name: vote
    namespace: vote
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30005

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: vote
    namespace: vote
  spec:
    template:
      spec:
        containers:
          - name: vote
            image: 789037212033.dkr.ecr.us-east-1.amazonaws.com/pull-request-vote-pr-5:a3b3d30211d2ad65a62c8f9f82557ec156614e35
            env:
            - name: VERSION
              value: a3b3d30211d2ad65a62c8f9f82557ec156614e35
