apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pull-request-master
  namespace: argocd # /!\ important
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: git@github.com:Duskfall/argocd-pull-request-infra.git
    targetRevision: HEAD
    path: manifests/overlays/master
  destination: 
    server: https://kubernetes.default.svc
    namespace: vote # default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
