bases:
- ../../base

# /!\ important !
# https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_namespacetransformer_
namespace: vote-pr-30358

patches:
- target:
    kind: Service
    name: vote
    namespace: vote
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30358

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: vote
    namespace: vote
  spec:
    template:
      spec:
        containers:
          - name: vote
            image: 789037212033.dkr.ecr.us-east-1.amazonaws.com/pull-request-vote-pr-30358:7c6ee0ab573617e2c272ddba19567229c69546b0
            env:
            - name: VERSION
              value: 7c6ee0ab573617e2c272ddba19567229c69546b0
