bases:
- ../../base

# /!\ important !
# https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_namespacetransformer_
namespace: vote-pr-10

patches:
- target:
    kind: Service
    name: vote
    namespace: vote
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30010

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: vote
    namespace: vote
  spec:
    template:
      spec:
        containers:
          - name: vote
            image: 789037212033.dkr.ecr.us-east-1.amazonaws.com/pull-request-vote-pr-10:289d927770b4894b4e90c9bad2c7acfc2325f38d
            env:
            - name: VERSION
              value: 289d927770b4894b4e90c9bad2c7acfc2325f38d
